# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BACKEND: ${{ secrets.BACKEND_HOST }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup wlcommon
        run: |
          cd wlcommon
          npm install
          npm run build
          ../getwlcommon.sh
          
      - name: Setup wlclient
        run: |
          cd wlclient
          npm install
          CI=false npm run build
        
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: wlclient/build # The folder the action should deploy.
